config/routes.rb
GpuDosing::Application.routes.draw do
  resources :valvegroups

  resources :valves

  resources :sizes

  resources :companies

  resources :searches

  resources :balls

  resources :gaskets

  resources :heads

  resources :lines

  match '/kits',    :to => 'kits#show'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/admin',   :to => 'pages#admin'
  match '/find',    :to => 'pages#find'
  match '/import',  :to => 'pages#import' 
  

   root :to => "pages#home"

end

app/models/valve.rb
# == Schema Information
# Schema version: 20101221183627
#
# Table name: valves
#
#  id            :integer         not null, primary key
#  partnumber    :integer
#  head_id       :integer
#  gasket_id     :integer
#  ball_id       :integer
#  valvegroup_id :integer
#  iskit         :boolean
#  created_at    :datetime
#  updated_at    :datetime
#

class Valve < ActiveRecord::Base
  belongs_to :head
  belongs_to :gasket
  belongs_to :ball
  belongs_to :valvegroup
  
  validates :partnumber,  :presence => true
  validates :head_id,     :presence => true
  validates :gasket_id,   :presence => true
  validates :ball_id,     :presence => true
end

app/controllers/valves_controller.rb
class ValvesController < ApplicationController
  # GET /valves
  # GET /valves.xml
  def index
    @valves = Valve.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @valves }
    end
  end

  # GET /valves/1
  # GET /valves/1.xml
  def show
    @valve = Valve.find(params[:id])
    
    @size = Size.where(:valvegroup_id => Size.find(:all, :conditions => {:id => @valve[:id]}))

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @valve }
    end
  end

  # GET /valves/new
  # GET /valves/new.xml
  def new
    @valve = Valve.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @valve }
    end
  end

  # GET /valves/1/edit
  def edit
    @valve = Valve.find(params[:id])
  end

  # POST /valves
  # POST /valves.xml
  def create
    @valve = Valve.new(params[:valve])

    respond_to do |format|
      if @valve.save
        format.html { redirect_to(@valve, :notice => 'Valve was successfully created.') }
        format.xml  { render :xml => @valve, :status => :created, :location => @valve }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @valve.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /valves/1
  # PUT /valves/1.xml
  def update
    @valve = Valve.find(params[:id])

    respond_to do |format|
      if @valve.update_attributes(params[:valve])
        format.html { redirect_to(@valve, :notice => 'Valve was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @valve.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /valves/1
  # DELETE /valves/1.xml
  def destroy
    @valve = Valve.find(params[:id])
    @valve.destroy

    respond_to do |format|
      format.html { redirect_to(valves_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/valves_helper.rb
module ValvesHelper
end

app/views/valves/_form.html.erb
<%= form_for(@valve) do |f| %>
  <% if @valve.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@valve.errors.count, "error") %> prohibited this valf from being saved:</h2>

      <ul>
      <% @valve.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :partnumber %><br />
    <%= f.text_field :partnumber %>
  </div>
  <div class="field">
    <%= f.label :head_id %><br />
    <%= f.collection_select :head_id, Head.all, :id, :material, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :gasket_id %><br />
    <%= f.collection_select :gasket_id, Gasket.all, :id, :material, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :ball_id %><br />
    <%= f.collection_select :ball_id, Ball.all, :id, :material, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :valvegroup_id %><br />
    <%= f.collection_select :valvegroup_id, Valvegroup.all, :id, :description, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :iskit %><br />
    <%= f.check_box :iskit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/valves/edit.html.erb
<h1>Editing valve</h1>

<%= render 'form' %>

<%= link_to 'Show', @valve %> |
<%= link_to 'Back', valves_path %>

app/views/valves/index.html.erb
<h1>Listing valves</h1>

<table>
  <tr>
    <th>Part number</th>
    <th>Head</th>
    <th>Gasket</th>
    <th>Ball</th>
    <th>Group</th>
    <th>Is kit</th>
    <th></th>
    <th></th>
  </tr>

<% @valves.each do |valve| %>
  <tr>
    <td><%= link_to valve.partnumber, valve %></td>
    <td><%= valve.head.material %></td>
    <td><%= valve.gasket.material %></td>
    <td><%= valve.ball.material %></td>
    <td><%= valve.valvegroup.description %></td>
    <td><%= valve.iskit %></td>
    <td><%= link_to 'Edit', edit_valve_path(valve) %></td>
    <td><%= link_to 'Destroy', valve, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Valve', new_valve_path %>

app/views/valves/new.html.erb
<h1>New valve</h1>

<%= render 'form' %>

<%= link_to 'Back', valves_path %>

app/views/valves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Part number:</b>
  <%= @valve.partnumber %>
</p>

<p>
  <b>Head:</b>
  <%= @valve.head.material %>
</p>

<p>
  <b>Gasket:</b>
  <%= @valve.gasket.material %>
</p>

<p>
  <b>Ball:</b>
  <%= @valve.ball.material %>
</p>

<p>
  <b>Is kit:</b>
  <%= @valve.iskit %>
</p>

<p>
  <b>Group:</b>
  <%= @valve.valvegroup.description %>
</p>

<p>
  <b>This kit applies to the following pumps:</b><br />
  <% @size.each do |group| %>
    <%= group.line.name %> <%= group.flow_pressure %><br />
  <% end %>
</p>

<%= link_to 'Edit', edit_valve_path(@valve) %> |
<%= link_to 'Back', valves_path %> |
<%= link_to 'New Valve', new_valve_path %>