config/routes.rb
GpuDosing::Application.routes.draw do
  resources :valvegroups

  resources :valves

  resources :sizes

  resources :companies

  resources :searches

  resources :balls

  resources :gaskets

  resources :heads

  resources :lines

  match '/kits',    :to => 'kits#show'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/admin',   :to => 'pages#admin'
  match '/find',    :to => 'pages#find'
  match '/import',  :to => 'pages#import' 
  

   root :to => "pages#home"

end

app/models/search.rb
# == Schema Information
# Schema version: 20101221183627
#
# Table name: searches
#
#  id         :integer         not null, primary key
#  line_id    :integer
#  flow       :integer
#  pressure   :integer
#  head_id    :integer
#  gasket_id  :integer
#  ball_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Search < ActiveRecord::Base
  
  belongs_to :dnsize
  belongs_to :head
  belongs_to :gasket
  belongs_to :ball
  belongs_to :line
  
  def dnsize
    @dnsize ||= find_dnsize
  end
  
  private
  
  def find_dnsize
    Dnsize.search(params[:search])
  end
  
  
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.xml
  def index
    @searches = Search.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.xml
  def show
    @search = Search.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.xml
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
  end

  # POST /searches
  # POST /searches.xml
  def create
    @search = Search.new(params[:search])

    respond_to do |format|
      if @search.save
        format.html { redirect_to(@search, :notice => 'Search was successfully created.') }
        format.xml  { render :xml => @search, :status => :created, :location => @search }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.xml
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to(@search, :notice => 'Search was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.xml
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to(searches_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table>
  <tr>
    <td><div class="field">
      <%= f.label :line_id %><br />
      <%= f.collection_select :line_id, Line.all, :id, :name, :include_blank => true %>
    </div></td>
    <td><div class="field">
      <%= f.label :flow %><br />
      <%= f.text_field :flow, :size => 5 %>
    </div></td>
    <td><div class="field">
      <%= f.label :pressure %><br />
      <%= f.text_field :pressure, :size => 5 %>
    </div></td>
    <td><div class="field">
      <%= f.label :head_id %><br />
      <%= f.collection_select :head_id, Head.all, :id, :material, :include_blank => true %>
    </div></td>
    <td><div class="field">
      <%= f.label :gasket_id %><br />
      <%= f.collection_select :gasket_id, Gasket.all, :id, :material, :include_blank => true %>
    </div></td>
    <td><div class="field">
      <%= f.label :ball_id %><br />
      <%= f.collection_select :ball_id, Ball.all, :id, :material, :include_blank => true %>
    </div></td>
  </tr>
</table> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/_kits.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

Tie the model search result to the form using the searchlogic named scope.
Create a partial and run it from the show action.  It should show @search.valvekit

<html lang="en">
  <head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	  <title>_kits.html</title>
	  <%= javascript_include_tag :defaults %>
	  <%= yield :head %>
  </head>
  <body>
  <%= yield %>
  </body>
</html>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<h1>Listing searches</h1>

<table>
  <tr>
    <th>Line</th>
    <th>Flow</th>
    <th>Pressure</th>
    <th>Head</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @searches.each do |search| %>
  <tr>
    <td><%= search.line_id %></td>
    <td><%= search.flow %></td>
    <td><%= search.pressure %></td>
    <td><%= search.head_id %></td>
    <td><%= link_to 'Show', search %></td>
    <td><%= link_to 'Edit', edit_search_path(search) %></td>
    <td><%= link_to 'Destroy', search, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Line:</b>
  <%= @search.line_id %>
</p>

<p>
  <b>Flow:</b>
  <%= @search.flow %>
</p>

<p>
  <b>Pressure:</b>
  <%= @search.pressure %>
</p>

<p>
  <b>Head:</b>
  <%= @search.head.material %>
</p>


<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>