config/routes.rb
GpuDosing::Application.routes.draw do
  resources :valvegroups

  resources :valves

  resources :sizes

  resources :companies

  resources :searches

  resources :balls

  resources :gaskets

  resources :heads

  resources :lines

  match '/kits',    :to => 'kits#show'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/admin',   :to => 'pages#admin'
  match '/find',    :to => 'pages#find'
  match '/import',  :to => 'pages#import' 
  

   root :to => "pages#home"

end

app/models/ball.rb
# == Schema Information
# Schema version: 20101221183627
#
# Table name: balls
#
#  id         :integer         not null, primary key
#  material   :string(255)
#  typekey    :string(255)
#  tradename  :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Ball < ActiveRecord::Base
  has_many :valves
  # has_many :diaphragms
  # has_many :services
  # has_many :checkballs
  
  validates :typekey,   :presence => true,
                        :uniqueness => {:case_sensitive => false}
  validates :tradename, :presence => true,
                        :uniqueness => {:case_sensitive => false}
  
  def code
    "#{typekey} - #{tradename}"
  end
end

app/models/company.rb
# == Schema Information
# Schema version: 20101221183627
#
# Table name: companies
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Company < ActiveRecord::Base
end

app/models/gasket.rb
# == Schema Information
# Schema version: 20101221183627
#
# Table name: gaskets
#
#  id         :integer         not null, primary key
#  material   :string(255)
#  typekey    :string(255)
#  tradename  :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Gasket < ActiveRecord::Base
  has_many :valves
  # has_many :diaphragms
  # has_many :services
  
  validates :typekey,   :presence => true,
                        :uniqueness => {:case_sensitive => false}
  validates :tradename, :presence => true,
                        :uniqueness => {:case_sensitive => false}

  def code
    "#{typekey} - #{tradename}"
  end
end

app/models/head.rb
# == Schema Information
# Schema version: 20101221183627
#
# Table name: heads
#
#  id         :integer         not null, primary key
#  material   :string(255)
#  typekey    :string(255)
#  tradename  :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Head < ActiveRecord::Base
  has_many :valves
  # has_many :diaphragms
  # has_many :services
  # has_many :pumpheads
  
  validates :typekey,   :presence => true,
                        :uniqueness => {:case_sensitive => false}
  validates :tradename, :presence => true,
                        :uniqueness => {:case_sensitive => false}
  
  def code
    "#{typekey} - #{tradename}"
  end
end

app/models/line.rb
# == Schema Information
# Schema version: 20101221183627
#
# Table name: lines
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Line < ActiveRecord::Base
  
  has_many :valves
  has_many :sizes
  # has_many :checkballs
  # has_many :pumpheads
  
  belongs_to :company
  
  validates :name,  :presence => true,
                    :uniqueness => {:case_sensitive => false}
  
end

app/models/search.rb
# == Schema Information
# Schema version: 20101221183627
#
# Table name: searches
#
#  id         :integer         not null, primary key
#  line_id    :integer
#  flow       :integer
#  pressure   :integer
#  head_id    :integer
#  gasket_id  :integer
#  ball_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Search < ActiveRecord::Base
  
  belongs_to :dnsize
  belongs_to :head
  belongs_to :gasket
  belongs_to :ball
  belongs_to :line
  
  def dnsize
    @dnsize ||= find_dnsize
  end
  
  private
  
  def find_dnsize
    Dnsize.search(params[:search])
  end
  
  
  
end

app/models/size.rb
# == Schema Information
# Schema version: 20101221183627
#
# Table name: sizes
#
#  id            :integer         not null, primary key
#  flow          :integer
#  pressure      :integer
#  line_id       :integer
#  valvegroup_id :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class Size < ActiveRecord::Base
  
  belongs_to :line
  belongs_to :valvegroup
  
  def flow_pressure
    "#{flow} - #{pressure}"
  end
end

app/models/valve.rb
# == Schema Information
# Schema version: 20101221183627
#
# Table name: valves
#
#  id            :integer         not null, primary key
#  partnumber    :integer
#  head_id       :integer
#  gasket_id     :integer
#  ball_id       :integer
#  valvegroup_id :integer
#  iskit         :boolean
#  created_at    :datetime
#  updated_at    :datetime
#

class Valve < ActiveRecord::Base
  belongs_to :head
  belongs_to :gasket
  belongs_to :ball
  belongs_to :valvegroup
  
  validates :partnumber,  :presence => true
  validates :head_id,     :presence => true
  validates :gasket_id,   :presence => true
  validates :ball_id,     :presence => true
end

app/models/valvegroup.rb
# == Schema Information
# Schema version: 20101221183627
#
# Table name: valvegroups
#
#  id          :integer         not null, primary key
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Valvegroup < ActiveRecord::Base
  
  has_many :valves
  has_many :sizes
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  # return a title on a per page basis
  def title
    base_title = "Grundfos Pumps Dosing Parts Selector"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/balls_helper.rb
module BallsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/gaskets_helper.rb
module GasketsHelper
end

app/helpers/heads_helper.rb
module HeadsHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  # Fill this in so it returns the kit object if only 1 kit remains from the filter
  # Handle returning text explanations if the results are 0 or many kits
  # Should I add conditional statements to the find view to properly render the return of this helper?
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/valvegroups_helper.rb
module ValvegroupsHelper
end

app/helpers/valves_helper.rb
module ValvesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Admin", admin_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<!--  <%= image_tag("logo.png", :alt => "Sample App", :class => "round") %> -->
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Find parts", find_path %></li>
      <li><%= link_to "Help", '#' %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= javascript_include_tag :defaults %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/_found_kit.html.erb
<div>
  <% if found_kit.iskit? %>
    <h3><%= found_kit.class %> Kit</h3>
    <%= found_kit.partnumber %><br />
    <p>This is a complete kit.  An order for quantity 1 will provide the parts for a complete pump.</p> 
  <% else %>
    <h3><%= found_kit.class%> Part</h3>
    <%= found_kit.partnumber %><br />
    <p>This is not a kit.  An order for quantity 1 will only provide a single part.</p>
  <% end %>
</div>

app/views/pages/_kit.html.erb
<div class="kit">
  <% if kit.length > 1 %>
    <h3><%= kit.first.class %></h3>
    <%= render 'not_enough' %>
    <% else if kit.length < 1 %>
      <h3>Valve kit</h3>
      <%= render 'no_kit' %>
      <% else %>
        <%= render :partial => 'found_kit', :object => kit %>
    <% end %>
  <% end %>
</div>
<br />

app/views/pages/_no_kit.html.erb
<div>
  No kit was found!  Would you like to request it?
  <%= mail_to("me@domain.com", nil, :subject => "New parts kit request", :body => Head.find_by_id(params[:head][:head_id]).typekey) %>
</div>

app/views/pages/_not_enough.html.erb
<div>
  You didn't provide enough information for us to select a kit!
</div>

app/views/pages/about.html.erb
<h1>About</h1>
<p>This site was created by Willis F. Jackson III with 
  the kind assistance of skilled programmers from the Kansas City Ruby Meetup Group.</p>

app/views/pages/admin.html.erb
<h1>Administration Panel</h1>
<table class="panel" summary="Administration Panel">
  <tr>
    <td class="admin">
      <h4>Pump Attributes</h4>
      <ul>
        <li><%= link_to "Product Lines", lines_path %></li>
        <li><%= link_to "Companies", companies_path %></li>
        <li><%= link_to "Pump Sizes", sizes_path %></li>
        <li><%= link_to "Head Materials", heads_path %></li>
        <li><%= link_to "Gasket Materials", gaskets_path %></li>
        <li><%= link_to "Ball Materials", balls_path %></li>
      </ul>
    </td>
    <td class="admin">
      <h4>Available Kits</h4>
      <ul>
        <li><%= link_to "Service Kits", '#' %></li>
        <li><%= link_to "Valve Kits", valves_path %></li>
        <li><%= link_to "Diaphragm Kits", '#' %></li>
      </ul>
    </td>
  </tr>
  <tr>
    <td class="admin">
      <h4>Kit Groups</h4>
      <ul>
        <li><%= link_to "Valve Groups", valvegroups_path %></li>
      </ul>
    </td>
  </tr>
</table>

app/views/pages/contact.html.erb
<h1>Contact us</h1>
<p>If you need assistance with this application, please reach us
  <a href="mailto:gpu-water@grundfos.com?Subject=Parts%20Selector%20Assistance">here.</a>
</p>

app/views/pages/find.html.erb
<h1>Find parts and kits</h1>

<%= form_tag(find_path, :method => "get") do %>
<table>
  <tr>
    <td><div class="field">
      <%= label :line_id, "Line" %><br />
      <%= collection_select :line,
                            :line_id,
                            Line.all,
                            :id,
                            :name,
                            {:include_blank => true,
                              :selected => (if params[:line].nil? then :default else params[:line][:line_id].to_i end)} %>
    </div></td>
    <td><div class="field">
      <%= label :size_id, "Size" %><br />
      <%= collection_select :size,
                            :size_id,
                            Size.all,
                            :id,
                            :flow_pressure,
                            {:selected => (if params[:size].nil? then :default else params[:size][:size_id].to_i end)} %>
    </div></td>
    <td><div class="field">
      <%= label :head_id, "Head" %><br />
      <%= collection_select :head,
                            :head_id,
                            Head.all,
                            :id,
                            :code,
                            {:include_blank => true,
                              :selected => (if params[:head].nil? then :default else params[:head][:head_id].to_i end)} %>
    </div></td>
    <td><div><br />
      -X/
    </div></td>
    <td><div class="field">
      <%= label :gasket_id, "Gasket" %><br />
      <%= collection_select :gasket,
                            :gasket_id,
                            Gasket.all,
                            :id,
                            :code,
                            {:include_blank => true,
                              :selected => (if params[:gasket].nil? then :default else params[:gasket][:gasket_id].to_i end)} %>
    </div></td>
    <td><div><br />
      /
    </div></td>
    <td><div class="field">
      <%= label :ball_id, "Ball" %><br />
      <%= collection_select :ball,
                            :ball_id,
                            Ball.all,
                            :id,
                            :code,
                            {:include_blank => true,
                              :selected => (if params[:ball].nil? then :default else params[:ball][:ball_id].to_i end)} %>
    </div></td>
    <td><div><br />
      -X-21XXX
    </div></td>
  </tr>
</table>
<div class="actions">
  <%= submit_tag "Search", :name => nil %>
</div>
<% end %>
<br />
<div class="results">
  <%= render :partial => 'kit', :locals => {:kit => @valve} %>
</div>
<div class="debug">
  <h1>Ignore everything below this text</h1>
  <p>It is only here so I can troubleshoot the application before everything is finished.  It will be removed before the site is finished.</p>
  <b>Valve kit</b><br />
  <% @valve.each do |kit| %>
    <%= kit.partnumber %> | <%= kit.valvegroup.description %><br />
  <% end %>
  <%= @numb %> kits returned
</div>

app/views/pages/home.html.erb
<h1>Grundfos US Dosing Parts Search</h1>
<p>You can quickly and easily identify the repair parts you need for your dosing pump using this site.  If any parts are missing, don't forget to request them.</p>

app/views/pages/import.html.erb
<h1>Import</h1>
<%= @results.first.flow %>